/* =========================================================
   DATA.JS — CONCERT DATA (AUTO INGESTED FROM YOUR PDFs)
   Right lane: Dad (lane: "dad")
   Left lane: Miles (lane: "miles")
   Bridge: Shared dates (lane: "both")

   Notes
   1) Random stray numbers found in the PDFs were ignored.
   2) Bridge entries come from BOTH CONCERTS.pdf.
   3) Per entry YouTube links are intentionally not included.
   4) Fill the playlist links below when you create the playlists.
   ========================================================= */

const playlistLinks = {
  dad: "PASTE_DADS_PLAYLIST_URL_HERE",
  miles: "PASTE_MILES_PLAYLIST_URL_HERE",
  both: "PASTE_SHARED_PLAYLIST_URL_HERE"
};

const concerts = [
  {
    id: "dad-19790901",
    date: "1979-09-01",
    year: 1979,
    lane: "dad",
    artist: "KISS",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19830325",
    date: "1983-03-25",
    year: 1983,
    lane: "dad",
    artist: "Def Leppard, Billy Squier",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19830508",
    date: "1983-05-08",
    year: 1983,
    lane: "dad",
    artist: "Journey, Bryan Adams",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19860401",
    date: "1986-04-01",
    year: 1986,
    lane: "dad",
    artist: "Rush",
    venue: "Brendan Byrne Arena",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19860404",
    date: "1986-04-04",
    year: 1986,
    lane: "dad",
    artist: "Rush",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19860428",
    date: "1986-04-28",
    year: 1986,
    lane: "dad",
    artist: "Metallica, Ozzy Osbourne",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19861102",
    date: "1986-11-02",
    year: 1986,
    lane: "dad",
    artist: "Triumph, Yngwie Malmsteen",
    venue: "Brendan Byrne Arena",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19870407",
    date: "1987-04-07",
    year: 1987,
    lane: "dad",
    artist: "Cinderella, Bon Jovi",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19871018",
    date: "1987-10-18",
    year: 1987,
    lane: "dad",
    artist: "Def Leppard, Tesla",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19871207",
    date: "1987-12-07",
    year: 1987,
    lane: "dad",
    artist: "Rush, Tommy Shaw",
    venue: "Brendan Byrne Arena",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19871209",
    date: "1987-12-09",
    year: 1987,
    lane: "dad",
    artist: "Rush, Tommy Shaw",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19881018",
    date: "1988-10-18",
    year: 1988,
    lane: "dad",
    artist: "Prince",
    venue: "Spectrum",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "dad-19881022",
    date: "1988-10-22",
    year: 1988,
    lane: "dad",
    artist: "Van Halen",
    venue: "Spectrum",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "dad-19890308",
    date: "1989-03-08",
    year: 1989,
    lane: "dad",
    artist: "Bon Jovi, Skid Row",
    venue: "Spectrum",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "dad-19890710",
    date: "1989-07-10",
    year: 1989,
    lane: "dad",
    artist: "Grateful Dead, Los Lobos",
    venue: "Giants Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19891211",
    date: "1989-12-11",
    year: 1989,
    lane: "dad",
    artist: "Mötley Crüe, Warrant",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19900422",
    date: "1990-04-22",
    year: 1990,
    lane: "dad",
    artist: "Rush",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19900707",
    date: "1990-07-07",
    year: 1990,
    lane: "dad",
    artist: "Billy Joel",
    venue: "Orlando Arena",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19910820",
    date: "1991-08-20",
    year: 1991,
    lane: "dad",
    artist: "Jane's Addiction, Nine Inch Nails, Siouxsie and the Banshees, Butthole Surfers, Living Colour, Ice-T, Body Count, Rollins Band",
    venue: "Lollapalooza 1991",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19911201",
    date: "1991-12-01",
    year: 1991,
    lane: "dad",
    artist: "Rush, Vinnie Moore",
    venue: "Spectrum",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "dad-19911203",
    date: "1991-12-03",
    year: 1991,
    lane: "dad",
    artist: "Rush",
    venue: "Spectrum",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "dad-19911207",
    date: "1991-12-07",
    year: 1991,
    lane: "dad",
    artist: "Rush",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19911213",
    date: "1991-12-13",
    year: 1991,
    lane: "dad",
    artist: "Guns N' Roses",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19920315",
    date: "1992-03-15",
    year: 1992,
    lane: "dad",
    artist: "Rush, Primus",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19930728",
    date: "1993-07-28",
    year: 1993,
    lane: "dad",
    artist: "Tool, Alice in Chains, Rage Against the Machine, Arrested Development, Dinosaur Jr., Fishbone",
    venue: "Lollapalooza 1993",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19930803",
    date: "1993-08-03",
    year: 1993,
    lane: "dad",
    artist: "Peter Gabriel",
    venue: "Orlando Arena",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19931005",
    date: "1993-10-05",
    year: 1993,
    lane: "dad",
    artist: "Depeche Mode",
    venue: "Orlando Arena",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940118",
    date: "1994-01-18",
    year: 1994,
    lane: "dad",
    artist: "Janet Jackson",
    venue: "Orlando Arena",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940227",
    date: "1994-02-27",
    year: 1994,
    lane: "dad",
    artist: "Rush, Candlebox",
    venue: "Miami Arena",
    city: "Miami",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940301",
    date: "1994-03-01",
    year: 1994,
    lane: "dad",
    artist: "Rush, Candlebox",
    venue: "Orlando Arena",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940302",
    date: "1994-03-02",
    year: 1994,
    lane: "dad",
    artist: "Rush, Candlebox",
    venue: "Jacksonville Memorial Coliseum",
    city: "Jacksonville",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940304",
    date: "1994-03-04",
    year: 1994,
    lane: "dad",
    artist: "Rush, Candlebox",
    venue: "ThunderDome",
    city: "St. Petersburg",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940821",
    date: "1994-08-21",
    year: 1994,
    lane: "dad",
    artist: "Elton John & Billy Joel",
    venue: "Florida Citrus Bowl",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940825",
    date: "1994-08-25",
    year: 1994,
    lane: "dad",
    artist: "The Smashing Pumpkins, Beastie Boys, George Clinton and the P-Funk All Stars, The Breeders, A Tribe Called Quest, L7, Green Day, Cypress Hill, The Verve, The Pharcyde, Luscious Jackson, The Black Crowes",
    venue: "Lollapalooza 1994",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19940904",
    date: "1994-09-04",
    year: 1994,
    lane: "dad",
    artist: "Stone Temple Pilots, Jawbox, Meat Puppets",
    venue: "Ocean Center",
    city: "Daytona Beach",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19940925",
    date: "1994-09-25",
    year: 1994,
    lane: "dad",
    artist: "Green Day",
    venue: "The Edge",
    city: "Orlando",
    state: "FL",
    country: "USA"
  },
  {
    id: "dad-19950729",
    date: "1995-07-29",
    year: 1995,
    lane: "dad",
    artist: "Sonic Youth, Hole, Beck, Elastica, The Mighty Mighty Bosstones",
    venue: "Lollapalooza 1995",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19950919",
    date: "1995-09-19",
    year: 1995,
    lane: "dad",
    artist: "Eric Clapton",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19950928",
    date: "1995-09-28",
    year: 1995,
    lane: "dad",
    artist: "Belly",
    venue: "Malibu Shore Club",
    city: "Lido Beach",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19960711",
    date: "1996-07-11",
    year: 1996,
    lane: "dad",
    artist: "Metallica, Soundgarden, Wu-Tang Clan, Girls Against Boys, Screaming Trees, Ben Folds Five",
    venue: "Lollapalooza 1996",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19960728",
    date: "1996-07-28",
    year: 1996,
    lane: "dad",
    artist: "KISS",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19961126",
    date: "1996-11-26",
    year: 1996,
    lane: "dad",
    artist: "Stone Temple Pilots",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19961205",
    date: "1996-12-05",
    year: 1996,
    lane: "dad",
    artist: "Def Leppard",
    venue: "",
    city: "Johannesburg Stadium",
    state: "Johannesburg",
    country: "South Africa"
  },
  {
    id: "dad-19961214",
    date: "1996-12-14",
    year: 1996,
    lane: "dad",
    artist: "Rush",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19961215",
    date: "1996-12-15",
    year: 1996,
    lane: "dad",
    artist: "Rush",
    venue: "Continental Airlines Arena",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19961229",
    date: "1996-12-29",
    year: 1996,
    lane: "dad",
    artist: "KISS",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19970601",
    date: "1997-06-01",
    year: 1997,
    lane: "dad",
    artist: "U2",
    venue: "Giants Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-19970607",
    date: "1997-06-07",
    year: 1997,
    lane: "dad",
    artist: "Patti Smith, Fun Lovin' Criminals, Ben Harper & The Innocent Criminals, Sonic Youth, Porno for Pyros, A Tribe Called Quest, Biz Markie, U2, Noel Gallagher, Foo Fighters, Radiohead",
    venue: "Tibetan Freedom Concert 1997",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19970608",
    date: "1997-06-08",
    year: 1997,
    lane: "dad",
    artist: "Blur, Eddie Vedder & Mike McCready, Beastie Boys, Björk, The Mighty Mighty Bosstones, De La Soul, Alanis Morissette, The Wallflowers, R.E.M.",
    venue: "Tibetan Freedom Concert 1997",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19970623",
    date: "1997-06-23",
    year: 1997,
    lane: "dad",
    artist: "No Doubt, Weezer",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19970625",
    date: "1997-06-25",
    year: 1997,
    lane: "dad",
    artist: "Rush",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19970807",
    date: "1997-08-07",
    year: 1997,
    lane: "dad",
    artist: "Live, Luscious Jackson",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19970815",
    date: "1997-08-15",
    year: 1997,
    lane: "dad",
    artist: "Sheryl Crow, Wilco",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19970826",
    date: "1997-08-26",
    year: 1997,
    lane: "dad",
    artist: "311, De La Soul",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19980530",
    date: "1998-05-30",
    year: 1998,
    lane: "dad",
    artist: "Green Day, Third Eye Blind, Scott Weiland, The Offspring, Soul Asylum, Fuel, Ben Folds Five",
    venue: "WXRK 92.3 Dysfunctional Family Picnic 1998",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-19980611",
    date: "1998-06-11",
    year: 1998,
    lane: "dad",
    artist: "Ben Folds Five, Beck",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19980719",
    date: "1998-07-19",
    year: 1998,
    lane: "dad",
    artist: "Jimmy Page & Robert Plant",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19980806",
    date: "1998-08-06",
    year: 1998,
    lane: "dad",
    artist: "Jimmy Buffett",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19980824",
    date: "1998-08-24",
    year: 1998,
    lane: "dad",
    artist: "Beastie Boys, A Tribe Called Quest",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19981013",
    date: "1998-10-13",
    year: 1998,
    lane: "dad",
    artist: "Aerosmith, Fuel",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19981113",
    date: "1998-11-13",
    year: 1998,
    lane: "dad",
    artist: "Goo Goo Dolls",
    venue: "Roseland Ballroom",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19990627",
    date: "1999-06-27",
    year: 1999,
    lane: "dad",
    artist: "Foreigner",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19990807",
    date: "1999-08-07",
    year: 1999,
    lane: "dad",
    artist: "Roger Waters",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19990825",
    date: "1999-08-25",
    year: 1999,
    lane: "dad",
    artist: "Jeff Beck, Jonny Lang",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19990905",
    date: "1999-09-05",
    year: 1999,
    lane: "dad",
    artist: "The Moody Blues",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-19991009",
    date: "1999-10-09",
    year: 1999,
    lane: "dad",
    artist: "Wyclef Jean, Diddy, Mary J. Blige, Counting Crows, Jewel, Busta Rhymes, Bono, Jimmy Page & The Black Crowes, The Black Crowes, Sheryl Crow, Sting",
    venue: "NetAid 1999",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20000804",
    date: "2000-08-04",
    year: 2000,
    lane: "dad",
    artist: "Hot Tuna, The Allman Brothers Band",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20000812",
    date: "2000-08-12",
    year: 2000,
    lane: "dad",
    artist: "Red Hot Chili Peppers, Stone Temple Pilots, Fishbone",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20000825",
    date: "2000-08-25",
    year: 2000,
    lane: "dad",
    artist: "Pearl Jam, Sonic Youth",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20000829",
    date: "2000-08-29",
    year: 2000,
    lane: "dad",
    artist: "Jimmy Buffett",
    venue: "Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20010730",
    date: "2001-07-30",
    year: 2001,
    lane: "dad",
    artist: "Madonna",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20021024",
    date: "2002-10-24",
    year: 2002,
    lane: "dad",
    artist: "Rush",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20031001",
    date: "2003-10-01",
    year: 2003,
    lane: "dad",
    artist: "Bruce Springsteen",
    venue: "Shea Stadium",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20040513",
    date: "2004-05-13",
    year: 2004,
    lane: "dad",
    artist: "Yes",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20040623",
    date: "2004-06-23",
    year: 2004,
    lane: "dad",
    artist: "Van Halen",
    venue: "Continental Airlines Arena",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-20040811",
    date: "2004-08-11",
    year: 2004,
    lane: "dad",
    artist: "Rush",
    venue: "Radio City Music Hall",
    city: "New York",
    state: "NY",
    country: "USA Tommy Hilfiger at Jones Beach Theater"
  },
  {
    id: "dad-20040819",
    date: "2004-08-19",
    year: 2004,
    lane: "dad",
    artist: "Eminem",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20051101",
    date: "2005-11-01",
    year: 2005,
    lane: "dad",
    artist: "Gwen Stefani, Black Eyed Peas",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20060120",
    date: "2006-01-20",
    year: 2006,
    lane: "dad",
    artist: "The Rolling Stones",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20070702",
    date: "2007-07-02",
    year: 2007,
    lane: "dad",
    artist: "Rush",
    venue: "Nikon at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20070811",
    date: "2007-08-11",
    year: 2007,
    lane: "dad",
    artist: "Justin Timberlake",
    venue: "Mohegan Sun Arena",
    city: "Uncasville",
    state: "CT",
    country: "USA"
  },
  {
    id: "dad-20070917",
    date: "2007-09-17",
    year: 2007,
    lane: "dad",
    artist: "Rush",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20080714",
    date: "2008-07-14",
    year: 2008,
    lane: "dad",
    artist: "Rush",
    venue: "Nikon at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20080716",
    date: "2008-07-16",
    year: 2008,
    lane: "dad",
    artist: "Billy Joel",
    venue: "Shea Stadium",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20100724",
    date: "2010-07-24",
    year: 2010,
    lane: "dad",
    artist: "Rush",
    venue: "Nikon at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20110725",
    date: "2011-07-25",
    year: 2011,
    lane: "dad",
    artist: "Stone Temple Pilots",
    venue: "Williamsburg Waterfront",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20110930",
    date: "2011-09-30",
    year: 2011,
    lane: "dad",
    artist: "Black Eyed Peas",
    venue: "Central Park",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20120401",
    date: "2012-04-01",
    year: 2012,
    lane: "dad",
    artist: "Jimmy Buffett, The Avett Brothers",
    venue: "NCAA Big Dance Concert Series 2012",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20120427",
    date: "2012-04-27",
    year: 2012,
    lane: "dad",
    artist: "Chicago",
    venue: "NYCB Theatre at Westbury",
    city: "Westbury",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20120829",
    date: "2012-08-29",
    year: 2012,
    lane: "dad",
    artist: "Stone Temple Pilots",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20121013",
    date: "2012-10-13",
    year: 2012,
    lane: "dad",
    artist: "Fiona Apple",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20121022",
    date: "2012-10-22",
    year: 2012,
    lane: "dad",
    artist: "Rush",
    venue: "Barclays Center",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20150125",
    date: "2015-01-25",
    year: 2015,
    lane: "dad",
    artist: "Fleetwood Mac",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20150520",
    date: "2015-05-20",
    year: 2015,
    lane: "dad",
    artist: "The Who, Joan Jett & The Blackhearts",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20150610",
    date: "2015-06-10",
    year: 2015,
    lane: "dad",
    artist: "Aerosmith, Royal Machines",
    venue: "Petco Park",
    city: "San Diego",
    state: "CA",
    country: "USA"
  },
  {
    id: "dad-20150629",
    date: "2015-06-29",
    year: 2015,
    lane: "dad",
    artist: "Rush",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20160621",
    date: "2016-06-21",
    year: 2016,
    lane: "dad",
    artist: "Fitz and the Tantrums",
    venue: "Terminal 5",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20160726",
    date: "2016-07-26",
    year: 2016,
    lane: "dad",
    artist: "Radiohead",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20160805",
    date: "2016-08-05",
    year: 2016,
    lane: "dad",
    artist: "Pearl Jam",
    venue: "Fenway Park",
    city: "Boston",
    state: "MA",
    country: "USA"
  },
  {
    id: "dad-20160811",
    date: "2016-08-11",
    year: 2016,
    lane: "dad",
    artist: "Belly",
    venue: "The Bowery Ballroom",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20160924",
    date: "2016-09-24",
    year: 2016,
    lane: "dad",
    artist: "\"Weird Al\" Yankovic",
    venue: "Radio City Music Hall",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20161107",
    date: "2016-11-07",
    year: 2016,
    lane: "dad",
    artist: "Elvis Costello & The Imposters",
    venue: "Beacon Theatre",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20161116",
    date: "2016-11-16",
    year: 2016,
    lane: "dad",
    artist: "Fitz and the Tantrums",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20170215",
    date: "2017-02-15",
    year: 2017,
    lane: "both",
    artist: "Trombone Shorty & Orleans Avenue",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20170315",
    date: "2017-03-15",
    year: 2017,
    lane: "dad",
    artist: "Green Day",
    venue: "Barclays Center",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20170413",
    date: "2017-04-13",
    year: 2017,
    lane: "dad",
    artist: "Bon Jovi",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20170414",
    date: "2017-04-14",
    year: 2017,
    lane: "both",
    artist: "Billy Joel",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20170915",
    date: "2017-09-15",
    year: 2017,
    lane: "dad",
    artist: "Roger Waters",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20170917",
    date: "2017-09-17",
    year: 2017,
    lane: "dad",
    artist: "Sheryl Crow, The Avett Brothers, Nathaniel Rateliff & The Night Sweats",
    venue: "Outlaw Music Festival Camden 2017",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20170924",
    date: "2017-09-24",
    year: 2017,
    lane: "dad",
    artist: "Yes featuring Jon Anderson, Trevor Rabin, Rick Wakeman",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20170926",
    date: "2017-09-26",
    year: 2017,
    lane: "both",
    artist: "Paul McCartney",
    venue: "Nassau Veterans Memorial Coliseum",
    city: "Uniondale",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20180509",
    date: "2018-05-09",
    year: 2018,
    lane: "miles",
    artist: "Bon Jovi, Williams Honor",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20180714",
    date: "2018-07-14",
    year: 2018,
    lane: "dad",
    artist: "Foo Fighters",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20180718",
    date: "2018-07-18",
    year: 2018,
    lane: "dad",
    artist: "Weezer, Pixies",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20180727",
    date: "2018-07-27",
    year: 2018,
    lane: "dad",
    artist: "Preservation Hall Jazz Band",
    venue: "Patchogue Theatre for the Performing Arts",
    city: "Patchogue",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20180902",
    date: "2018-09-02",
    year: 2018,
    lane: "dad",
    artist: "Pearl Jam",
    venue: "Fenway Park",
    city: "Boston",
    state: "MA",
    country: "USA"
  },
  {
    id: "dad-20180904",
    date: "2018-09-04",
    year: 2018,
    lane: "dad",
    artist: "Pearl Jam",
    venue: "Fenway Park",
    city: "Boston",
    state: "MA",
    country: "USA"
  },
  {
    id: "dad-20190227",
    date: "2019-02-27",
    year: 2019,
    lane: "dad",
    artist: "John Mellencamp",
    venue: "Beacon Theatre",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20190325",
    date: "2019-03-25",
    year: 2019,
    lane: "dad",
    artist: "Mariah Carey",
    venue: "Radio City Music Hall",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20200218",
    date: "2020-02-18",
    year: 2020,
    lane: "dad",
    artist: "Fitz and the Tantrums",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20200227",
    date: "2020-02-27",
    year: 2020,
    lane: "dad",
    artist: "Branford Marsalis",
    venue: "Patchogue Theatre for the Performing Arts",
    city: "Patchogue",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210620",
    date: "2021-06-20",
    year: 2021,
    lane: "dad",
    artist: "Foo Fighters",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210810",
    date: "2021-08-10",
    year: 2021,
    lane: "dad",
    artist: "Jimmy Buffett",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210811",
    date: "2021-08-11",
    year: 2021,
    lane: "dad",
    artist: "Squeeze, Daryl Hall & John Oates",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210831",
    date: "2021-08-31",
    year: 2021,
    lane: "dad",
    artist: "311",
    venue: "Long Island Community Hospital Amphitheater",
    city: "Farmingville",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210917",
    date: "2021-09-17",
    year: 2021,
    lane: "dad",
    artist: "The Black Crowes",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20210918",
    date: "2021-09-18",
    year: 2021,
    lane: "dad",
    artist: "Pearl Jam, The Avett Brothers, Dr. Dog",
    venue: "Sea.Hear.Now Festival 2021",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20220609",
    date: "2022-06-09",
    year: 2022,
    lane: "dad",
    artist: "Miranda Lambert, Little Big Town, The Cadillac Three",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220610",
    date: "2022-06-10",
    year: 2022,
    lane: "dad",
    artist: "Blues Traveler, Jewel, Train",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220624",
    date: "2022-06-24",
    year: 2022,
    lane: "dad",
    artist: "Mötley Crüe, Def Leppard, Poison, Joan Jett & The Blackhearts",
    venue: "Citi Field",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220715",
    date: "2022-07-15",
    year: 2022,
    lane: "dad",
    artist: "Brian Wilson, Chicago",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220722",
    date: "2022-07-22",
    year: 2022,
    lane: "dad",
    artist: "Mitski, The Weather Station",
    venue: "Radio City Music Hall",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220811",
    date: "2022-08-11",
    year: 2022,
    lane: "dad",
    artist: "Lady Gaga",
    venue: "MetLife Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "dad-20220813",
    date: "2022-08-13",
    year: 2022,
    lane: "dad",
    artist: "Roger Waters",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220823",
    date: "2022-08-23",
    year: 2022,
    lane: "dad",
    artist: "Rod Stewart, Cheap Trick",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20220824",
    date: "2022-08-24",
    year: 2022,
    lane: "both",
    artist: "twenty one pilots, Peter McPoland",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220901",
    date: "2022-09-01",
    year: 2022,
    lane: "dad",
    artist: "Ben Folds",
    venue: "NYCB Theatre at Westbury",
    city: "Westbury",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20220917-01",
    date: "2022-09-17",
    year: 2022,
    lane: "dad",
    artist: "Stevie Nicks, My Morning Jacket, Gary Clark Jr., Culture Club, FLETCHER, The Backseat Lovers",
    venue: "Sea.Hear.Now Festival 2022",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20220917-02",
    date: "2022-09-17",
    year: 2022,
    lane: "dad",
    artist: "Peach Pit",
    venue: "Sea.Hear.Now Festival 2022",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20220918",
    date: "2022-09-18",
    year: 2022,
    lane: "dad",
    artist: "Green Day, IDLES, Wet Leg, Michael Franti & Spearhead, Cage the Elephant",
    venue: "Sea.Hear.Now Festival 2022",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20221001",
    date: "2022-10-01",
    year: 2022,
    lane: "dad",
    artist: "The Killers, Johnny Marr",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20221014",
    date: "2022-10-14",
    year: 2022,
    lane: "both",
    artist: "The Smashing Pumpkins, Jane's Addiction",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230512",
    date: "2023-05-12",
    year: 2023,
    lane: "dad",
    artist: "Babyface, Anita Baker",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230605",
    date: "2023-06-05",
    year: 2023,
    lane: "dad",
    artist: "John Mellencamp",
    venue: "Beacon Theatre",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230713",
    date: "2023-07-13",
    year: 2023,
    lane: "dad",
    artist: "Elvis Costello & The Imposters, Nick Lowe & Los Straitjackets",
    venue: "Beacon Theatre",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230722",
    date: "2023-07-22",
    year: 2023,
    lane: "dad",
    artist: "CAKE",
    venue: "The Rooftop at Pier 17",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230725",
    date: "2023-07-25",
    year: 2023,
    lane: "dad",
    artist: "Fitz and the Tantrums, Brother Elsey",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230729",
    date: "2023-07-29",
    year: 2023,
    lane: "dad",
    artist: "Gov't Mule, Nathaniel Rateliff & The Night Sweats, Willie Nelson",
    venue: "Outlaw Music Festival Bethel 2023",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "miles-20230902",
    date: "2023-09-02",
    year: 2023,
    lane: "miles",
    artist: "The Offspring, Sum 41, Simple Plan",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20230908",
    date: "2023-09-08",
    year: 2023,
    lane: "dad",
    artist: "Sting, Joe Sumner",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20230909",
    date: "2023-09-09",
    year: 2023,
    lane: "both",
    artist: "Aerosmith, The Black Crowes",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20230916",
    date: "2023-09-16",
    year: 2023,
    lane: "both",
    artist: "The Killers, Greta Van Fleet, Royal Blood, Quincy Mumford, Yawn Mower",
    venue: "Sea.Hear.Now Festival 2023",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "both-20230917",
    date: "2023-09-17",
    year: 2023,
    lane: "both",
    artist: "The Beach Boys, Weezer, Foo Fighters",
    venue: "Sea.Hear.Now Festival 2023",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20230920",
    date: "2023-09-20",
    year: 2023,
    lane: "dad",
    artist: "Eagles, Steely Dan",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20231005",
    date: "2023-10-05",
    year: 2023,
    lane: "dad",
    artist: "Henry Rollins",
    venue: "Landmark on Main Street",
    city: "Port Washington",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20231006",
    date: "2023-10-06",
    year: 2023,
    lane: "both",
    artist: "Belly, Parkington Sisters",
    venue: "The Gramercy Theatre",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20231111",
    date: "2023-11-11",
    year: 2023,
    lane: "both",
    artist: "Big Bad Voodoo Daddy",
    venue: "Epcot International Food & Wine Festival 2023",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "both-20231113",
    date: "2023-11-13",
    year: 2023,
    lane: "both",
    artist: "38 Special",
    venue: "Epcot International Food & Wine Festival 2023",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "miles-20240209",
    date: "2024-02-09",
    year: 2024,
    lane: "miles",
    artist: "¥$",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20240327",
    date: "2024-03-27",
    year: 2024,
    lane: "dad",
    artist: "Styx",
    venue: "Flagstar at Westbury Music Fair",
    city: "Westbury",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20240329",
    date: "2024-03-29",
    year: 2024,
    lane: "dad",
    artist: "Academy of St Martin in the Fields",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20240405",
    date: "2024-04-05",
    year: 2024,
    lane: "dad",
    artist: "Alexa Tarantino",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240525",
    date: "2024-05-25",
    year: 2024,
    lane: "both",
    artist: "Ringo Starr & His All Starr Band",
    venue: "The Venetian Theatre",
    city: "Las Vegas",
    state: "NV",
    country: "USA"
  },
  {
    id: "both-20240629",
    date: "2024-06-29",
    year: 2024,
    lane: "both",
    artist: "Bob Dylan, Robert Plant & Alison Krauss, Lukas Nelson",
    venue: "Outlaw Music Festival 2024",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20240710",
    date: "2024-07-10",
    year: 2024,
    lane: "dad",
    artist: "Janet Jackson, Nelly",
    venue: "Barclays Center",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240717",
    date: "2024-07-17",
    year: 2024,
    lane: "both",
    artist: "Foo Fighters, Pretenders",
    venue: "Citi Field",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240721",
    date: "2024-07-21",
    year: 2024,
    lane: "both",
    artist: "blink-182, Pierce the Veil, EKKSTACY",
    venue: "Citi Field",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20240730",
    date: "2024-07-30",
    year: 2024,
    lane: "miles",
    artist: "Limp Bizkit, Corey Feldman, RIFF RAFF",
    venue: "PNC Bank Arts Center",
    city: "Holmdel",
    state: "NJ",
    country: "USA"
  },
  {
    id: "both-20240805",
    date: "2024-08-05",
    year: 2024,
    lane: "both",
    artist: "Green Day, The Smashing Pumpkins, Rancid",
    venue: "Citi Field",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20240807",
    date: "2024-08-07",
    year: 2024,
    lane: "miles",
    artist: "Steve Winwood, The Doobie Brothers",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240808",
    date: "2024-08-08",
    year: 2024,
    lane: "both",
    artist: "The Beach Boys, Dave Mason",
    venue: "Northwell at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240822",
    date: "2024-08-22",
    year: 2024,
    lane: "both",
    artist: "Lynyrd Skynyrd, ZZ Top, Outlaws",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240901",
    date: "2024-09-01",
    year: 2024,
    lane: "both",
    artist: "Yes, Deep Purple, Hannah Wicklund",
    venue: "Northwell Health at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20240903",
    date: "2024-09-03",
    year: 2024,
    lane: "dad",
    artist: "Pearl Jam, Glen Hansard",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240904",
    date: "2024-09-04",
    year: 2024,
    lane: "both",
    artist: "Pearl Jam, Glen Hansard",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20240907",
    date: "2024-09-07",
    year: 2024,
    lane: "both",
    artist: "Pearl Jam, Glen Hansard",
    venue: "Wells Fargo Center",
    city: "Philadelphia",
    state: "PA",
    country: "USA"
  },
  {
    id: "miles-20240913",
    date: "2024-09-13",
    year: 2024,
    lane: "miles",
    artist: "Bowling for Soup, Wheatus",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20240915",
    date: "2024-09-15",
    year: 2024,
    lane: "dad",
    artist: "Pearl Jam, Glen Hansard",
    venue: "Fenway Park",
    city: "Boston",
    state: "MA",
    country: "USA"
  },
  {
    id: "both-20240928",
    date: "2024-09-28",
    year: 2024,
    lane: "both",
    artist: "Noah Kahan, Goo Goo Dolls, Fleet Foxes, Boyz II Men, Grace Potter, Thee Sacred Souls",
    venue: "Soundside Music Festival 2024",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "miles-20240929",
    date: "2024-09-29",
    year: 2024,
    lane: "miles",
    artist: "Gregory Alan Isakov, Drew Holcomb & the Neighbors, Bleachers, Jack White, Greta Van Fleet, Norah Jones, Teddy Swims",
    venue: "Soundside Music Festival 2024",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "both-20241001",
    date: "2024-10-01",
    year: 2024,
    lane: "both",
    artist: "Toad the Wet Sprocket, Barenaked Ladies",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241006",
    date: "2024-10-06",
    year: 2024,
    lane: "miles",
    artist: "Everclear, Marcy Playground",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20241027",
    date: "2024-10-27",
    year: 2024,
    lane: "dad",
    artist: "René Marie",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241102",
    date: "2024-11-02",
    year: 2024,
    lane: "miles",
    artist: "America",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20241106",
    date: "2024-11-06",
    year: 2024,
    lane: "both",
    artist: "David Gilmour",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20241108",
    date: "2024-11-08",
    year: 2024,
    lane: "both",
    artist: "MAGIC!",
    venue: "Epcot International Food & Wine Festival 2024",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "both-20241110",
    date: "2024-11-10",
    year: 2024,
    lane: "both",
    artist: "Parmalee",
    venue: "Epcot International Food & Wine Festival 2024",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20241112",
    date: "2024-11-12",
    year: 2024,
    lane: "dad",
    artist: "Blues Traveler, Cody Dickinson",
    venue: "Florida Theatre",
    city: "Jacksonville",
    state: "FL",
    country: "USA"
  },
  {
    id: "both-20241119",
    date: "2024-11-19",
    year: 2024,
    lane: "both",
    artist: "Trombone Shorty & Orleans Avenue, New Breed Brass Band",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241123",
    date: "2024-11-23",
    year: 2024,
    lane: "miles",
    artist: "Don McLean",
    venue: "Flagstar at Westbury Music Fair",
    city: "Westbury",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20241129",
    date: "2024-11-29",
    year: 2024,
    lane: "both",
    artist: "Mammoth, Creed, 3 Doors Down",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241203",
    date: "2024-12-03",
    year: 2024,
    lane: "miles",
    artist: "Jhené Aiko, Jessie Reyez, Shenseea, UMI, Kiana Ledé",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241213",
    date: "2024-12-13",
    year: 2024,
    lane: "miles",
    artist: "They Might Be Giants",
    venue: "Kings Theatre",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20241231",
    date: "2024-12-31",
    year: 2024,
    lane: "miles",
    artist: "Billy Joel, Jason Bonham's Led Zeppelin Evening",
    venue: "UBS Arena",
    city: "Elmont",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250119",
    date: "2025-01-19",
    year: 2025,
    lane: "miles",
    artist: "Will Butler + Sister Squares",
    venue: "Joe's Pub",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250131",
    date: "2025-01-31",
    year: 2025,
    lane: "miles",
    artist: "American Football, Wishy",
    venue: "District Music Hall",
    city: "Norwalk",
    state: "CT",
    country: "USA"
  },
  {
    id: "miles-20250201",
    date: "2025-02-01",
    year: 2025,
    lane: "miles",
    artist: "Oolong, Jam Poetry, MooseCreek Park, Jockey",
    venue: "VFW Post 7277",
    city: "Massapequa",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250211",
    date: "2025-02-11",
    year: 2025,
    lane: "miles",
    artist: "Boyz II Men",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250301",
    date: "2025-03-01",
    year: 2025,
    lane: "miles",
    artist: "Cinema Stare",
    venue: "VFW Post 7277",
    city: "Massapequa",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250403",
    date: "2025-04-03",
    year: 2025,
    lane: "both",
    artist: "Deftones, The Mars Volta",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250429",
    date: "2025-04-29",
    year: 2025,
    lane: "both",
    artist: "Pearl Jam, Dead Pioneers",
    venue: "State Farm Arena",
    city: "Atlanta",
    state: "GA",
    country: "USA"
  },
  {
    id: "miles-20250508",
    date: "2025-05-08",
    year: 2025,
    lane: "miles",
    artist: "Kendrick Lamar & SZA, Mustard",
    venue: "MetLife Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "miles-20250510",
    date: "2025-05-10",
    year: 2025,
    lane: "miles",
    artist: "The Crane Wives",
    venue: "Brooklyn Steel",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250518",
    date: "2025-05-18",
    year: 2025,
    lane: "both",
    artist: "Pearl Jam, Teen Jesus and the Jean Teasers",
    venue: "PPG Paints Arena",
    city: "Pittsburgh",
    state: "PA",
    country: "USA"
  },
  {
    id: "miles-20250531",
    date: "2025-05-31",
    year: 2025,
    lane: "miles",
    artist: "Skycamefalling",
    venue: "The Paramount",
    city: "Huntington",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20250603",
    date: "2025-06-03",
    year: 2025,
    lane: "dad",
    artist: "Metallica, Pantera, Suicidal Tendencies",
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    state: "GA",
    country: "USA"
  },
  {
    id: "miles-20250620",
    date: "2025-06-20",
    year: 2025,
    lane: "miles",
    artist: "Macseal, Cinema Stare, Emperor X",
    venue: "VFW Post 7277",
    city: "Massapequa",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250712",
    date: "2025-07-12",
    year: 2025,
    lane: "miles",
    artist: "\"Weird Al\" Yankovic",
    venue: "Madison Square Garden",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250715",
    date: "2025-07-15",
    year: 2025,
    lane: "both",
    artist: "Creed, Daughtry, Mammoth",
    venue: "Northwell at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250729",
    date: "2025-07-29",
    year: 2025,
    lane: "miles",
    artist: "Linkin Park, PVRIS",
    venue: "Barclays Center",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20250803",
    date: "2025-08-03",
    year: 2025,
    lane: "dad",
    artist: "The Avett Brothers",
    venue: "Tilles Center for the Performing Arts",
    city: "Brookville",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250803",
    date: "2025-08-03",
    year: 2025,
    lane: "miles",
    artist: "The Offspring, Jimmy Eat World, New Found Glory",
    venue: "Northwell at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20250810",
    date: "2025-08-10",
    year: 2025,
    lane: "miles",
    artist: "The Doobie Brothers, The Coral Reefer Band",
    venue: "Northwell at Jones Beach Theater",
    city: "Wantagh",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20250813",
    date: "2025-08-13",
    year: 2025,
    lane: "dad",
    artist: "The Black Keys",
    venue: "Forest Hills Stadium",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250831",
    date: "2025-08-31",
    year: 2025,
    lane: "both",
    artist: "Oasis, Cage the Elephant, Cast",
    venue: "MetLife Stadium",
    city: "East Rutherford",
    state: "NJ",
    country: "USA"
  },
  {
    id: "miles-20250906",
    date: "2025-09-06",
    year: 2025,
    lane: "miles",
    artist: "Bob Dylan, Waxahatchee, Willie Nelson, Sheryl Crow",
    venue: "Outlaw Music Festival Hartford 2025",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20250914",
    date: "2025-09-14",
    year: 2025,
    lane: "dad",
    artist: "blink-182, Lenny Kravitz, Public Enemy, 4 Non Blondes",
    venue: "Sea.Hear.Now Festival 2025",
    city: "",
    state: "",
    country: ""
  },
  {
    id: "dad-20250918",
    date: "2025-09-18",
    year: 2025,
    lane: "dad",
    artist: "Wet Leg, mary in the junkyard",
    venue: "Brooklyn Paramount",
    city: "Brooklyn",
    state: "NY",
    country: "USA"
  },
  {
    id: "both-20250920",
    date: "2025-09-20",
    year: 2025,
    lane: "both",
    artist: "Eric Clapton, The Wallflowers",
    venue: "Mohegan Sun Arena",
    city: "Uncasville",
    state: "CT",
    country: "USA"
  },
  {
    id: "dad-20251005",
    date: "2025-10-05",
    year: 2025,
    lane: "dad",
    artist: "Blues Traveler, Garrett Howell",
    venue: "Patchogue Theatre for the Performing Arts",
    city: "Patchogue",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20251006",
    date: "2025-10-06",
    year: 2025,
    lane: "dad",
    artist: "Marvelous 3",
    venue: "Irving Plaza",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20251024",
    date: "2025-10-24",
    year: 2025,
    lane: "dad",
    artist: "Belly",
    venue: "Sony Hall",
    city: "New York",
    state: "NY",
    country: "USA"
  },
  {
    id: "miles-20251108",
    date: "2025-11-08",
    year: 2025,
    lane: "miles",
    artist: "Playboi Carti, Destroy Lonely, Ken Carson, Homixide Gang, ApolloRed1",
    venue: "PeoplesBank Arena",
    city: "Hartford",
    state: "CT",
    country: "USA"
  },
  {
    id: "dad-20251121",
    date: "2025-11-21",
    year: 2025,
    lane: "dad",
    artist: "LCD Soundsystem",
    venue: "Knockdown Center",
    city: "Queens",
    state: "NY",
    country: "USA"
  },
  {
    id: "dad-20251125",
    date: "2025-11-25",
    year: 2025,
    lane: "dad",
    artist: "Natalie Merchant",
    venue: "Adler Hall | New York Society for Ethical Culture",
    city: "New York",
    state: "NY",
    country: "USA"
  }
];

/* End of data.js */
